services:

  postgres:
    image: postgres:15
    container_name: onevote_postgres
    restart: always
    environment:
      POSTGRES_USER: onevote
      POSTGRES_PASSWORD: onevote
      POSTGRES_DB: onevote
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onevote"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: onevote_redis
    ports:
      - "6379:6379"

  election:
    build: ./backend/services/election
    container_name: election_service
    ports:
      - "8003:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg2://onevote:onevote@postgres:5432/election_db

volumes:
  postgres_data:
