"""init

Revision ID: 40873c71da9f
Revises: 
Create Date: 2026-03-29 09:01:06.090860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40873c71da9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ONGOING', 'COMPLETED', name='electionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligible_voters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('voter_id', sa.String(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligible_voters_roll_no'), 'eligible_voters', ['roll_no'], unique=False)
    op.create_index(op.f('ix_eligible_voters_voter_id'), 'eligible_voters', ['voter_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('election_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_candidates_selectable', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    op.drop_table('positions')
    op.drop_index(op.f('ix_eligible_voters_voter_id'), table_name='eligible_voters')
    op.drop_index(op.f('ix_eligible_voters_roll_no'), table_name='eligible_voters')
    op.drop_table('eligible_voters')
    op.drop_table('elections')
    # ### end Alembic commands ###
