"""changes in election table adding org_id to election

Revision ID: c40065b47be5
Revises: 40873c71da9f
Create Date: 2026-04-01 12:00:21.486253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40065b47be5'
down_revision: Union[str, Sequence[str], None] = '40873c71da9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('org_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_elections_org_id'), 'elections', ['org_id'], unique=False)
    op.add_column('eligible_voters', sa.Column('unique_identifier', sa.String(), nullable=False))
    op.alter_column('eligible_voters', 'voter_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_eligible_voters_roll_no'), table_name='eligible_voters')
    op.create_index(op.f('ix_eligible_voters_unique_identifier'), 'eligible_voters', ['unique_identifier'], unique=False)
    op.drop_column('eligible_voters', 'roll_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligible_voters', sa.Column('roll_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_eligible_voters_unique_identifier'), table_name='eligible_voters')
    op.create_index(op.f('ix_eligible_voters_roll_no'), 'eligible_voters', ['roll_no'], unique=False)
    op.alter_column('eligible_voters', 'voter_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('eligible_voters', 'unique_identifier')
    op.drop_index(op.f('ix_elections_org_id'), table_name='elections')
    op.drop_column('elections', 'org_id')
    # ### end Alembic commands ###
