"""init

Revision ID: 954d7a60988e
Revises: 
Create Date: 2026-03-29 09:01:08.837945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954d7a60988e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_anchors',
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('final_block_hash', sa.String(), nullable=False),
    sa.Column('blockchain_txn_id', sa.String(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('anchor_id'),
    sa.UniqueConstraint('election_id')
    )
    op.create_table('vote_participation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('has_voted', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_participation_election_id'), 'vote_participation', ['election_id'], unique=False)
    op.create_index(op.f('ix_vote_participation_user_id'), 'vote_participation', ['user_id'], unique=False)
    op.create_table('votes',
    sa.Column('vote_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('user_reference_hash', sa.String(), nullable=False),
    sa.Column('vote_hash', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('block_index', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_index(op.f('ix_votes_election_id'), 'votes', ['election_id'], unique=False)
    op.create_index(op.f('ix_votes_organisation_id'), 'votes', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_votes_user_reference_hash'), 'votes', ['user_reference_hash'], unique=False)
    op.create_table('voting_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_voting_tokens_election_id'), 'voting_tokens', ['election_id'], unique=False)
    op.create_index(op.f('ix_voting_tokens_user_id'), 'voting_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voting_tokens_user_id'), table_name='voting_tokens')
    op.drop_index(op.f('ix_voting_tokens_election_id'), table_name='voting_tokens')
    op.drop_table('voting_tokens')
    op.drop_index(op.f('ix_votes_user_reference_hash'), table_name='votes')
    op.drop_index(op.f('ix_votes_organisation_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_election_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_vote_participation_user_id'), table_name='vote_participation')
    op.drop_index(op.f('ix_vote_participation_election_id'), table_name='vote_participation')
    op.drop_table('vote_participation')
    op.drop_table('blockchain_anchors')
    # ### end Alembic commands ###
