export const ERROR_CODES = {
  UNKNOWN: "UNKNOWN",
  NETWORK_ERROR: "NETWORK_ERROR",

  AUTH_ERROR: "AUTH_ERROR",
  ORG_ERROR: "ORG_ERROR",
  IDENTITY_ERROR: "INDENTITY_ERROR",
  BIOMETRIC_ERROR: "BIOMETRIC_ERROR",
  ELECTION_ERROR: "ELECTION_ERROR",
  VOTING_ERROR: "VOTING_ERROR",
  NOTIFICATION_ERROR: "NOTIFICATION_ERROR",
  
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",

  SERVER_ERROR: "SERVER_ERROR",
  CSRF_MISSING: "CSRF_MISSING",
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];