events {}

http {
    upstream auth {
        server auth:8000;
    }

    upstream identity {
        server identity:8000;
    }

    upstream biometric {
        server biometric:8000;
    }

    upstream organisation {
        server organisation:8000;
    }

    upstream election {
        server election:8000;
    }

    upstream voting {
        server voting:8000;
    }

    upstream notification {
        server notification:8000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth/;
        }

        location /identity/ {
            proxy_pass http://identity/;
        }

        location /biometric/ {
            proxy_pass http://biometric/;
        }

        location /org/ {
            proxy_pass http://organisation/;
        }

        location /election/ {
            proxy_pass http://election/;
        }

        location /voting/ {
            proxy_pass http://voting/;
        }

        location /notification/ {
            proxy_pass http://notification/;
        }
    }
}