events {}

http {
    upstream auth {
        server auth:8000;
    }

    upstream identity {
        server identity:8000;
    }

    upstream biometric {
        server biometric:8000;
    }

    upstream organisation {
        server organisation:8000;
    }

    upstream election {
        server election:8000;
    }

    upstream voting {
        server voting:8000;
    }

    upstream notification {
        server notification:8000;
    }

    server {
        listen 80;

        # 🔥 CORS Headers
        # add_header 'Access-Control-Allow-Origin' '$http_origin' always;
        # add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        # add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-INTERNAL-KEY,X-CSRF-Token' always;
        # add_header 'Access-Control-Allow-Credentials' 'true' always;

        # if ($request_method = 'OPTIONS') {
        #     add_header 'Access-Control-Allow-Origin' '$http_origin' always;
        #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        #     add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-INTERNAL-KEY,X-CSRF-Token' always;
        #     add_header 'Access-Control-Allow-Credentials' 'true' always;
        #     add_header 'Access-Control-Max-Age' 1728000;
        #     add_header 'Content-Type' 'text/plain; charset=utf-8';
        #     add_header 'Content-Length' 0;
        #     return 204;
        # }

        location /auth/ {
            proxy_pass http://auth/;
        }

        location /identity/ {
            proxy_pass http://identity/;
        }

        location /biometric/ {
            proxy_pass http://biometric/;
        }

        location /org/ {
            proxy_pass http://organisation/;
        }

        location /election/ {
            proxy_pass http://election/;
        }

        location /voting/ {
            proxy_pass http://voting/;
        }

        location /notification/ {
            proxy_pass http://notification/;
        }
    }
}