"""create tables

Revision ID: 6bdbd786dd24
Revises: 43f5085d3808
Create Date: 2026-03-30 06:57:16.587816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdbd786dd24'
down_revision: Union[str, Sequence[str], None] = '43f5085d3808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('face_encoding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_profile_user_id'), 'biometric_profile', ['user_id'], unique=True)
    op.create_table('biometric_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_session_token'), 'biometric_session', ['token'], unique=True)
    op.create_index(op.f('ix_biometric_session_user_id'), 'biometric_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biometric_session_user_id'), table_name='biometric_session')
    op.drop_index(op.f('ix_biometric_session_token'), table_name='biometric_session')
    op.drop_table('biometric_session')
    op.drop_index(op.f('ix_biometric_profile_user_id'), table_name='biometric_profile')
    op.drop_table('biometric_profile')
    # ### end Alembic commands ###
