version: '3.9'

services:
  auth:
    build: .
    container_name: auth_service_dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    # environment:
    #   - DATABASE_URL=postgresql://auth_user:auth_pass@auth_postgres:5432/auth_db
    #   - REDIS_URL=redis://auth_redis:6379/0
    #   - API_ENV=development
    #   - JWT_SECRET=supersecret-dev-jwt-key
    #   - INTERNAL_SECRET=strong823oihsndSJJHDSHioh
    volumes:
      - .:/app  
    depends_on:
      - auth_postgres
      - auth_redis

  auth_postgres:
    image: postgres:15
    container_name: auth_postgres_local
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432" # Changed port to avoid conflict with root postgres
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

  auth_redis:
    image: redis:7
    container_name: auth_redis_local
    ports:
      - "6380:6379" # Changed port to avoid conflict with root redis

volumes:
  auth_pg_data:
